name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Check out the code
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
      # Run Maven tests
    - name: Run Maven tests
      run: mvn verify -Dskip.integration.tests=true
